"""Run the corpus through upstream's string rewriter and through ORM pushdown; render Markdown.

Usage (writes ``docs/gap-report.md``; the PostgreSQL columns need ``DATABASE_URL``)::

    PYTHONPATH=. uv run python -m tests.gap.report > docs/gap-report.md

The upstream rewriter is not at fault for any row here: it was never written for
ORM-rendered SQL, and its own docs say so. The table measures the gap, not a defect.
"""

from __future__ import annotations

import os
import sys
from typing import Any

import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tests.settings")
django.setup()

from django.db import connection  # noqa: E402
from django.test.utils import setup_databases, teardown_databases  # noqa: E402
from tolap_core import SqlDialect, prepare_sql_query  # noqa: E402

from django_tolap.pushdown import prepare_queryset  # noqa: E402
from tests.gap.corpus import CORPUS, POLICIES  # noqa: E402
from tests.harness.seed import seed  # noqa: E402

DIALECTS = {"postgresql": SqlDialect.postgres, "sqlite": SqlDialect.ansi}


def _executes(sql: str) -> str:
    """Whether the rewriter's output runs on this database as rendered by ``str(query)``."""
    try:
        with connection.cursor() as cur:
            cur.execute(sql)
            cur.fetchall()
    except Exception as exc:  # noqa: BLE001 - the error class is the finding
        return f"no ({type(exc).__name__})"
    return "yes"


def upstream_row(sql: str, policy: Any) -> dict[str, str]:
    prep = prepare_sql_query(sql, policy, dialect=DIALECTS.get(connection.vendor, SqlDialect.ansi))
    if not prep.allowed:
        return {"outcome": f"refused: {prep.denial_reason}", "executes": "-"}
    pushed = "rewritten" if prep.rewritten else "unchanged"
    unpushed = ", ".join(f.field for f in prep.unpushable_filters) or "none"
    return {"outcome": f"{pushed}; unpushed: {unpushed}", "executes": _executes(prep.query)}


def ours_row(qs: Any, policy: Any) -> str:
    prep = prepare_queryset(qs, policy)
    if not prep.allowed:
        return f"refused: {prep.denial_reason}"
    pushed = len(prep.pushed_filters)
    total = pushed + len(prep.unpushable_filters)
    rows = len(list(prep.queryset)) if prep.queryset is not None else 0
    return f"pushed {pushed}/{total} filters, {len(prep.visible_fields)} visible cols, {rows} rows fetched"


def render() -> str:
    lines = [
        "# Gap report: upstream string rewriter vs ORM-native pushdown",
        "",
        f"Generated by `tests/gap/report.py` on vendor `{connection.vendor}` with `tolap-core` "
        "1.0.0. Each QuerySet is rendered with `str(qs.query)` and handed to upstream "
        "`prepare_sql_query`; the same QuerySet goes through `django_tolap.prepare_queryset`. "
        "Upstream's rewriter was never designed for ORM-rendered SQL (its docs say to use "
        "`postOnly` when an ORM owns the SQL); this table measures that gap.",
        "",
    ]
    for policy_name, policy in POLICIES.items():
        lines += [
            f"## Policy: {policy_name}",
            "",
            "| QuerySet | Shape | Upstream rewriter on `str(qs.query)` | Rewritten SQL executes? | django-tolap |",
            "| --- | --- | --- | --- | --- |",
        ]
        for name, factory, description in CORPUS:
            qs = factory()
            up = upstream_row(str(qs.query), policy)
            lines.append(
                f"| `{name}` | {description} | {up['outcome']} | {up['executes']} | {ours_row(qs, policy)} |"
            )
        lines.append("")
    refused = sum(
        1
        for p in POLICIES.values()
        for _, f, _ in CORPUS
        if not prepare_sql_query(
            str(f().query), p, dialect=DIALECTS.get(connection.vendor, SqlDialect.ansi)
        ).allowed
    )
    total = len(POLICIES) * len(CORPUS)
    lines += [
        "## Summary",
        "",
        f"- Upstream refused or left unchanged: see table; refused outright: {refused} of {total} (QuerySet, policy) pairs.",
        "- Django renders a default projection as an explicit column list, so any hidden column on the model makes the rewriter refuse the query (`validate_query` sees the column named).",
        '- Injected predicates are unqualified (`"region" = ...`), which is ambiguous once a join is present.',
        "- `str(qs.query)` is not executable SQL: parameters are interpolated without quoting, so string filters and dates fail to run.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    """Render against a throwaway test database (``test_<name>``), never the configured one."""
    old_config = setup_databases(verbosity=0, interactive=False)
    try:
        seed()
        sys.stdout.write(render())
    finally:
        teardown_databases(old_config, verbosity=0)


if __name__ == "__main__":
    main()
