# Generated by Django 6.1.1 on 2026-09-25 07:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField()),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_name', models.CharField(blank=True, max_length=128, null=True)),
                ('assignee_identifier', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'TOLAP audit event',
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('body', models.JSONField(help_text='The TOLAP policy definition (schema v1.0), verbatim.')),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TOLAP policy definition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_type', models.CharField(choices=[('user', 'user'), ('group', 'group'), ('role', 'role'), ('serviceAccount', 'serviceAccount')], max_length=32)),
                ('assignee_identifier', models.CharField(max_length=255)),
                ('tenant_id', models.CharField(blank=True, default='', help_text='Empty = any', max_length=255)),
                ('source_connection_id', models.CharField(blank=True, default='', help_text='Empty = any', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('granted_by', models.CharField(max_length=255)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='django_tolap.policydefinition', to_field='name')),
            ],
            options={
                'verbose_name': 'TOLAP policy assignment',
                'ordering': ['policy__name', 'assignee_type', 'assignee_identifier'],
                'indexes': [models.Index(fields=['assignee_type', 'assignee_identifier'], name='django_tola_assigne_27888b_idx'), models.Index(fields=['tenant_id'], name='django_tola_tenant__3dc898_idx')],
                'constraints': [models.UniqueConstraint(fields=('policy', 'assignee_type', 'assignee_identifier', 'tenant_id', 'source_connection_id'), name='django_tolap_assignment_unique')],
            },
        ),
    ]
