# Generated by Django 6.1.1 on 2026-09-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tolap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyassignment',
            name='source_connection_id',
            field=models.CharField(blank=True, default='', help_text='Empty = any', max_length=128),
        ),
        migrations.AlterField(
            model_name='policyassignment',
            name='tenant_id',
            field=models.CharField(blank=True, default='', help_text='Empty = any', max_length=128),
        ),
    ]
