# Generated by Django 6.1.1 on 2026-09-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=120)),
                ('ssn', models.CharField(max_length=11)),
                ('date_of_birth', models.DateField()),
                ('region', models.CharField(db_index=True, max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('score', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
